files:
  - README.md
dirs:
  - chocolate/
useGitIgnore: true
ignorePatterns:
  - pattern: '^http(s)?://localhost'
  - pattern: '^http(s)?://127.0.0.1'
  - pattern: "^ftp://[^\\s/$?#]*\\.[^\\s]*$"
  - pattern: "^https://github.com/JabRef/jabref-issue-melting-pot"
